var routerApp = angular.module('routerApp', ['ui.router']);
routerApp.config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/index');
    $stateProvider
        .state('index',{
            url:"/index",
            templateUrl:"dom/route/index.html"
        })
        .state('state1',{
            url:"/state1",
            templateUrl:"dom/route/a.html"
        })
        .state('state2',{
            url:"/state1",
            templateUrl:"dom/route/b.html"
        })
        .state('state3',{
            url:"/state1",
            templateUrl:"dom/route/c.html"
        })
        .state('state',{
            url:"/state",
            templateUrl:"dom/route/branch.html"
        })
        .state('state.main',{
            url:"/main",
            templateUrl:"dom/route/b.html"
        })
        .state('state.footer',{
            url:"/footer",
            templateUrl:"dom/route/c.html"
        })
        .state('project',{
            url:"/project",
            views:{
                '':{
                    templateUrl:"dom/dem/d-index.html"
                },
                'navbar@project':{
                    templateUrl:'dom/dem/navbar.html'
                },
                'main@project':{
                    templateUrl:'dom/dem/1.html'
                }
            }
        })
        .state('project.nav2',{
            url:"/nav2",
            views:{
                'main@project':{
                    templateUrl:'dom/dem/2.html'
                }
            }
        })
        .state('project.nav2.list1',{
            url:"/list1",
            views:{
                '':{
                    templateUrl:'dom/dem/list1.html'
                }
            }
        })
        .state('project.nav2.list2',{
            url:"/list2",
            views:{
                '':{
                    templateUrl:'dom/dem/list2.html'
                }
            }
        })
        .state('project.nav2.list3',{
            url:"/list3",
            views:{
                '':{
                    templateUrl:'dom/dem/list3.html'
                }
            }
        })
        .state('project.nav3',{
            url:"/nav3",
            views:{
                'main@project':{
                    templateUrl:'dom/dem/3.html'
                }
            }
        })
        .state('project.nav4',{
            url:"/nav4",
            views:{
                'main@project':{
                    templateUrl:'dom/dem/4.html'
                }
            }
        })
        .state('project.nav5',{
            url:"/nav5",
            views:{
                'main@project':{
                    templateUrl:'dom/dem/5.html'
                }
            }
        })
});